[package]
name = "jluniq"
version = "0.1.1"
authors = ["winebarrel <sugawara@winebarrel.jp>"]
edition = "2018"

[dependencies]
getopts = "0.2"
serde_json = "1.0"
anyhow = "1.0"

[dev-dependencies]
indoc = "1.0"
